package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"math/rand"
	"strconv"
	"time"

	"github.com/zlargon/gograph/graph/model"
	"github.com/zlargon/gograph/repository"
)

var (
	videoRepo repository.VideoRepository = repository.New()
)

// CreateVideo is the resolver for the createVideo field.
func (r *mutationResolver) CreateVideo(ctx context.Context, input model.NewVideo) (*model.Video, error) {
	rand.Seed(time.Now().UnixNano())

	video := &model.Video{
		ID:    strconv.Itoa(rand.Int()),
		URL:   input.URL,
		Title: input.Title,
		Author: &model.User{
			ID:   input.UserID,
			Name: "user " + input.UserID,
		},
	}

	videoRepo.Save(video)
	return video, nil
}

// Videos is the resolver for the videos field.
func (r *queryResolver) Videos(ctx context.Context) ([]*model.Video, error) {
	return videoRepo.FindAll(), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
